### ISSUE TITLE
Invoice still showing for event despite mentor deleting all registrations

### ISSUE THREAD

**Issue by evanbailey** [MelbourneHighSchoolRobotics/RCJA_Registration_System#432]
See 735 as an example (my account).

**Comment by peter-drew** [comment]
Originally this was a deliberate decision to ensure that invoice numbers don't increment rapidly when teams are deleted and then recreated. It is not difficult to change this behaviour, but does mean that if a mentor deletes and recreates a team a new invoice number and new invoice date will be created.

**Comment by evanbailey** [comment]
I like the idea of the invoice number not changing, could you just setup a UI control so the invoice isn't shown if the teams on the invoice = 0?

**Comment by peter-drew** [comment]
Developer note: Account for this when implementing #306

**Comment by peter-drew** [comment]
@evanbailey the changed behaviour is an invoice will not show in the mentor interface if the invoice amount is $0 (actually < 0.05 because floating point) and no payments have been made on the invoice. Is still visible in the admin, where it can be deleted if desired. Mentors can also still see the invoice if they go directly to it, such as through a link or browser history.

**Comment by evanbailey** [comment]
@peter-drew  Great, thanks.
